version: "2"

services:
  influxdb:
    image: influxdb:latest
    restart: always
    ports:
      - 8086:8086
    volumes:
      - /data/app/influxdb/data:/var/lib/influxdb
      - /data/app/influxdb/config:/etc/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${admin_password}
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=${telegraph_password}

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /data/app/grafana/data:/var/lib/grafana
      - /data/app/grafana/config:/etc/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${admin_password}
      - GF_SERVER_ENABLE_GZIP=true
