version: "2"

services:
  influxdb:
    image: influxdb:latest
    restart: always
    ports:
      - 8086:8086
    volumes:
      - /data/app/influxdb/data:/var/lib/influxdb
      - /data/app/influxdb/config:/etc/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${admin_password}
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=${telegraph_password}
