---
version: "2"
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Dubai
    volumes:
      - /data/app/sabnzbd/config:/config
      - /data/app/sabnzbd/downloads:/downloads
      - /data/app/sabnzbd/incomplete-downloads:/incomplete-downloads
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Dubai
    volumes:
      - /data/app/sonarr/config:/config
      - /data/media/Series:/tv
      - /data/app/sabnzbd/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped