---
version: "3.2"
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Dubai
    volumes:
      - type: bind
        source: /data/app/sabnzbd/config
        target: /config
      - type: bind
        source: /data/app/sabnzbd/downloads
        target: /downloads
      - type: bind
        source: /data/app/sabnzbd/incomplete-downloads
        target: /incomplete-downloads
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped