---
version: "2"

networks:
  traefik_external:
    ipam:
      driver: default
      config:
        - subnet: 172:16.238.0/24
          gateway: 172.16.238.1
  traefik_internal:
    internal: true
    ipam:
      driver: overlay
      config:
        - subnet: 172:16.239.0/24
          gateway: 172.16.239.1
  default:
    driver: bridge
    
    
services:
#  sabnzbd:
#    image: linuxserver/sabnzbd
#    container_name: sabnzbd
#    environment:
#      - PUID=$USER_ID
#      - PGID=$GROUP_ID
#      - TZ=$TIMEZONE
#    volumes:
#      - $APP_DIR/sabnzbd/config:/config
#      - $TMP_DIR/downloads:/downloads
#      - $APP_DIR/sabnzbd/incomplete-downloads:/incomplete-downloads
#    ports:
#      - 8080:8080
##      - 9090:9090
#    restart: unless-stopped
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - $APP_DIR/nzbget/config:/config
      - $TMP_DIR/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
    networks:
      - traefik_internal

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - $APP_DIR/sonarr/config:/config
      - $MEDIA_DIR/Series:/tv
      - $TMP_DIR/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - $APP_DIR/radarr/config:/config
      - $MEDIA_DIR/Movies:/movies
      - $TMP_DIR/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - $APP_DIR/lidarr/config:/config
      - $MEDIA_DIR/Music:/music
      - $TMP_DIR/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - $APP_DIR/bazarr/config:/config
      - $MEDIA_DIR/Movies:/movies
      - $MEDIA_DIR/Series:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
  nzbhydra2:
    image: hotio/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - $APP_DIR/nzbhydra2/config:/config
      - $APP_DIR/jackett/blackhole:/blackhole
    ports:
      - 5076:5076
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - $APP_DIR/jackett/config:/config
      - $APP_DIR/jackett/blackhole:/blackhole
    ports:
      - 9117:9117
    restart: unless-stopped
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - $APP_DIR/deluge/config:/config
      - $APP_DIR/jackett/blackhole:/blackhole
      - $APP_DIR/deluge/downloads:/downloads
      - $APP_DIR/deluge/incomplete-downloads:/incomplete-downloads
    restart: unless-stopped
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
    volumes:
      - $APP_DIR/tautulli/config:/config
#      - path to plex logs:/log
    ports:
      - 8181:8181
    restart: unless-stopped
  airsonic:
    image: linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TIMEZONE
      - JAVA_OPTS=-Dserver.use-forward-headers=true
    volumes:
      - $APP_DIR/airsonic/config:/config
      - $APP_DIR/airsonic/playlists:/playlists
      - $MEDIA_DIR/Music:/music
    ports:
      - 4040:4040
    restart: unless-stopped
  mymediaforalexa:
    image: bizmodeller/mymediaforalexa
    container_name: mymediaforalexa
    volumes:
      - $APP_DIR/mymediaforalexa/data:/datadir
      - $MEDIA_DIR/Music:/medialibrary
    ports:
      - 52050:52050
      - 52051:52051
    restart: unless-stopped
