version: "2"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8800:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
